# Generated by Django 3.2.13 on 2022-04-18 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coloring', '0002_posting_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='claimed',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='saved',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='total',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='posting',
            name='best_by',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='posting',
            name='qty',
            field=models.IntegerField(null=True),
        ),
    ]
