# Generated by Django 3.2.13 on 2022-04-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coloring', '0003_auto_20220418_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='claimed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='posting',
            name='rating_lister',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='posting',
            name='rating_taker',
            field=models.IntegerField(null=True),
        ),
    ]
