# Generated by Django 3.2.13 on 2022-04-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coloring', '0004_auto_20220419_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posting',
            name='rating_taker',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
