# Generated by Django 3.2.13 on 2022-04-22 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coloring', '0004_auto_20220419_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posting',
            name='rating_taker',
        ),
        migrations.AddField(
            model_name='user',
            name='rating_denom',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='rating_numer',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True),
        ),
    ]
