# Generated by Django 3.2.13 on 2022-04-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coloring', '0005_auto_20220422_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_image',
        ),
    ]
