# Generated by Django 3.2.13 on 2022-04-23 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coloring', '0005_auto_20220422_1903'),
        ('coloring', '0006_auto_20220422_1504'),
    ]

    operations = [
    ]
