# Generated by Django 3.2.13 on 2022-04-25 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coloring', '0007_merge_0005_auto_20220422_1903_0006_auto_20220422_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_one', models.CharField(max_length=40)),
                ('user_two', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('chat_storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coloring.chatstorage')),
            ],
        ),
        migrations.DeleteModel(
            name='User_Image',
        ),
    ]
