# Generated by Django 3.2.13 on 2022-04-29 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coloring', '0009_auto_20220427_0257'),
        ('coloring', '0009_user_total_ratings'),
    ]

    operations = [
    ]
